Support extract_outliers, quantize_4bit and dequantize_4bit with Device Abstraction PR.
ROCm/bitsandbytes pull request #23
Opened 2024-05-06 15:58 UTC by lcskrishna

2024-05-06 15:58 UTC, lcskrishna commented
[BitsAndBytes_UT_summary_05_06.log](https://github.com/ROCm/bitsandbytes/files/15223141/BitsAndBytes_UT_summary_05_06.log)

For the test failures - this PR needs to be cherry-picked:
https://github.com/ROCm/bitsandbytes/pull/21

2024-05-06 16:23 UTC, pnunna93 requested changes

2024-05-06 16:23 UTC, pnunna93 commented on bitsandbytes/backends/cuda.py
> +            blocksize = 128
Could we just override default value instead of hard coding it to 128 for HIP?

2024-05-06 16:23 UTC, pnunna93 commented on bitsandbytes/backends/cuda.py
> +            blocksize = 128
Same change needed here

2024-05-06 16:25 UTC, pnunna93 commented
> [BitsAndBytes_UT_summary_05_06.log](https://github.com/ROCm/bitsandbytes/files/15223141/BitsAndBytes_UT_summary_05_06.log)
> 
> For the test failures - this PR needs to be cherry-picked: #21

Just pushed the change into device_abstraction branch, please rebase and check

2024-05-07 13:16 UTC, lcskrishna commented
Latest unit tests runs: all successful after cherry-picking PRs. 
[BitsAndBytes_UT_summary_05_07.log](https://github.com/ROCm/bitsandbytes/files/15236028/BitsAndBytes_UT_summary_05_07.log)

2024-05-08 17:01 UTC, lcskrishna commented
[BitsAndBytes_UT_summary.log](https://github.com/ROCm/bitsandbytes/files/15252337/BitsAndBytes_UT_summary.log)

2024-05-08 17:06 UTC, merged